### ISSUE TITLE
AttributeError: 'GeoAxesSubplot' object has no attribute '_autoscaleXon'

### ISSUE THREAD

**Issue by abhisek-acharya** [localdevices/pyorc#107]
Error update after v0.3.3

ax = cam_config.plot(tiles="GoogleTiles", tiles_kwargs={"style": "satellite"})

AttributeError                            Traceback (most recent call last)
File ~/miniconda3/envs/pyorc/lib/python3.8/site-packages/matplotlib/pyplot.py:119, in _draw_all_if_interactive()
    117 def _draw_all_if_interactive():
    118     if matplotlib.is_interactive():
--> 119         draw_all()

File ~/miniconda3/envs/pyorc/lib/python3.8/site-packages/matplotlib/_pylab_helpers.py:132, in Gcf.draw_all(cls, force)
    130 for manager in cls.get_all_fig_managers():
    131     if force or manager.canvas.figure.stale:
--> 132         manager.canvas.draw_idle()

File ~/miniconda3/envs/pyorc/lib/python3.8/site-packages/matplotlib/backend_bases.py:2054, in FigureCanvasBase.draw_idle(self, *args, **kwargs)
   2052 if not self._is_idle_drawing:
   2053     with self._idle_draw_cntx():
-> 2054         self.draw(*args, **kwargs)

File ~/miniconda3/envs/pyorc/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py:405, in FigureCanvasAgg.draw(self)
    401 # Acquire a lock on the shared font cache.
    402 with RendererAgg.lock, \
    403      (self.toolbar._wait_cursor_for_draw_cm() if self.toolbar
    404       else nullcontext()):
--> 405     self.figure.draw(self.renderer)
    406     # A GUI class may be need to update a window using this draw, so
    407     # don't forget to call the superclass.
...
    947     bounds = self.get_xbound()
    948     self.set_xbound(max(bounds[0], self.projection.x_limits[0]),
    949                     min(bounds[1], self.projection.x_limits[1]))

AttributeError: 'GeoAxesSubplot' object has no attribute '_autoscaleXon'

**Comment by hcwinsemius** [comment]
This is if I recall well, a bug in cartopy that only appears on windows. Can you try to build a python environment with python 3.11 and see if the issue persists?

**Comment by abhisek-acharya** [comment]
After updating python to 3.11 problem got solved. I am on mac machine though. I request you to put minimum python version required in documentation.
